name: team_1d
description: Solar Space, a webtech-project
# version: 1.0.0

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  vector_math: any
#  path: ^1.4.1

dev_dependencies:
  build_runner: ^1.1.2
  build_web_compilers: ^1.0.0
  pedantic: ^1.0.0
